// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpNBSPDlQaX_NVy9v95wGUu14eHSHlgGo',
    appId: '1:566957478503:web:86c084cbcad286303bfac2',
    messagingSenderId: '566957478503',
    projectId: 'e-commerce-24560',
    authDomain: 'e-commerce-24560.firebaseapp.com',
    storageBucket: 'e-commerce-24560.appspot.com',
    measurementId: 'G-XFMQ9G1X56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwj07KBwx6zrPcoQH2DZUYXeUmUqs7PmM',
    appId: '1:566957478503:android:8f3cfa2c60d10c483bfac2',
    messagingSenderId: '566957478503',
    projectId: 'e-commerce-24560',
    storageBucket: 'e-commerce-24560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZKaGp3dMsZ0hdsY3os0u4XDDi3sjrP4',
    appId: '1:566957478503:ios:cc56c93694549b073bfac2',
    messagingSenderId: '566957478503',
    projectId: 'e-commerce-24560',
    storageBucket: 'e-commerce-24560.appspot.com',
    androidClientId: '566957478503-5qm1en1eljdahvrhb5dvg1ncf5j25tgt.apps.googleusercontent.com',
    iosClientId: '566957478503-d5gair20fvhm0eua0oq5m70334fhpsmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeZKaGp3dMsZ0hdsY3os0u4XDDi3sjrP4',
    appId: '1:566957478503:ios:7b7edee4457b583b3bfac2',
    messagingSenderId: '566957478503',
    projectId: 'e-commerce-24560',
    storageBucket: 'e-commerce-24560.appspot.com',
    androidClientId: '566957478503-5qm1en1eljdahvrhb5dvg1ncf5j25tgt.apps.googleusercontent.com',
    iosClientId: '566957478503-vup15t85ajmihplv20baeorkliuqjmaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
